version: "3.10"
services:
 app:
  build: .
  volumes:
   - .:/django
  ports:
   - 8000:8000
  image: app:django_netflix
  container_name: netflix_django_container
  command: python manage.py runserver 0.0.0.0:8000