# Generated by Django 5.0.2 on 2024-04-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(blank=True, max_length=200, null=True)),
                ('director_name', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('episodes_number', models.IntegerField(blank=True, null=True)),
                ('is_based_on_manga', models.BooleanField(default=False)),
            ],
        ),
    ]
