# Generated by Django 5.0.6 on 2024-06-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_anime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='director_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='eng_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
